In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report
import statsmodels.api as sm
import pandas as pd
import os

In [2]:
os.chdir("E:\\eDX - Analytics Edge\\Week2\\")

In [6]:
# Problem 1.1 - Creating Our First Model
climate_data=pd.read_csv("climate_change.csv")

In [7]:
climate_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Year      308 non-null    int64
 1   Month     308 non-null    int64
 2   MEI       308 non-null    float64
 3   CO2       308 non-null    float64
 4   CH4       308 non-null    float64
 5   N2O       308 non-null    float64
 6   CFC-11    308 non-null    float64
 7   CFC-12    308 non-null    float64
 8   TSI       308 non-null    float64
 9   Aerosols  308 non-null    float64
 10  Temp      308 non-null    float64
dtypes: float64(9), int64(2)
memory usage: 26.6 KB

In [8]:
# split the data into a training set, consisting of all the observations up to and including 2006, and a testing set \
# consisting of the remaining years. 
train_data = climate_data[climate_data["Year"] <= 2006]

In [10]:
train_data.describe()

,Year,Month,MEI,CO2,CH4,N2O,CFC-11,CFC-12,TSI,Aerosols,Temp
count,284.000000,284.000000,284.000000,284.000000,284.000000,284.000000,284.000000,284.000000,284.000000,284.000000,284.000000
mean,1994.661972,6.556338,0.341923,361.414261,1745.841479,311.657225,252.487092,494.217546,1366.101437,0.017721,0.247799
std,6.845996,3.446768,0.929639,11.439691,45.669846,4.758513,20.987671,59.046642,0.401283,0.030014,0.181136
min,1983.000000,1.000000,-1.586000,340.170000,1629.890000,303.677000,191.324000,350.113000,1365.426100,0.001600,-0.282000
25%,1989.000000,4.000000,-0.323000,352.315000,1716.347500,307.657000,249.557750,462.543000,1365.754550,0.002700,0.118000
50%,1995.000000,7.000000,0.308500,359.890000,1758.605000,310.849500,260.373500,522.089000,1366.054500,0.006200,0.232500
75%,2001.000000,10.000000,0.898000,370.585000,1781.637500,316.129250,267.448000,540.972750,1366.399275,0.014000,0.406500
max,2006.000000,12.000000,3.001000,384.980000,1808.150000,320.451000,271.494000,543.813000,1367.316200,0.149400,0.739000

In [11]:
test_data = climate_data[climate_data["Year"] > 2006]

In [12]:
test_data.describe()

,Year,Month,MEI,CO2,CH4,N2O,CFC-11,CFC-12,TSI,Aerosols,Temp
count,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000
mean,2007.500000,6.500000,-0.509792,384.674583,1796.957083,321.084708,245.890458,536.660417,1365.707737,0.004071,0.363000
std,0.510754,3.526299,0.640489,2.044560,11.398775,0.542589,1.371970,1.427480,0.031728,0.000605,0.107847
min,2007.000000,1.000000,-1.635000,380.900000,1771.890000,320.332000,244.080000,534.906000,1365.657000,0.003100,0.074000
25%,2007.000000,3.750000,-1.043750,383.065000,1792.377500,320.557750,244.615500,535.114000,1365.675175,0.003600,0.307000
50%,2007.500000,6.500000,-0.530500,384.525000,1798.045000,321.256000,246.180500,536.964000,1365.714550,0.004100,0.380000
75%,2008.000000,9.250000,-0.036000,386.137500,1803.535000,321.408750,246.593000,537.377000,1365.726250,0.004500,0.414000
max,2008.000000,12.000000,0.974000,388.500000,1814.180000,322.182000,248.372000,539.206000,1365.761600,0.005400,0.601000

In [16]:
# Problem 2.1 - Understanding the Model
X = sm.add_constant(train_data[["MEI","CO2", "CH4", "N2O", "CFC-11", "CFC-12", "TSI", "Aerosols"]])

In [18]:
# build a linear regression model to predict the dependent variable Temp
regTemp = sm.OLS(train_data["Temp"], X).fit()

In [19]:
# Problem 1.1 - Creating Our First Model
# Question 1: find model R2 (the "Multiple R-squared" value):
# Question 2: Which variables are significant in the model? We will consider a variable signficant only if the p-value \
# is below 0.05.

# R2 can be checked via summary of model
regTemp.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   Temp   R-squared:                       0.751
Model:                            OLS   Adj. R-squared:                  0.744
Method:                 Least Squares   F-statistic:                     103.6
Date:                Fri, 02 Oct 2020   Prob (F-statistic):           1.94e-78
Time:                        06:18:11   Log-Likelihood:                 280.10
No. Observations:                 284   AIC:                            -542.2
Df Residuals:                     275   BIC:                            -509.4
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -124.5943     19.887     -6.265      0.000    -163.744     -85.445
MEI            0.0642      0.006      9.923      0.000       0.051       0.077
CO2            0.0065      0.002      2.826      0.005       0.002       0.011
CH4            0.0001      0.001      0.240      0.810      -0.001       0.001
N2O           -0.0165      0.009     -1.930      0.055      -0.033       0.000
CFC-11        -0.0066      0.002     -4.078      0.000      -0.010      -0.003
CFC-12         0.0038      0.001      3.757      0.000       0.002       0.006
TSI            0.0931      0.015      6.313      0.000       0.064       0.122
Aerosols      -1.5376      0.213     -7.210      0.000      -1.957      -1.118
==============================================================================
Omnibus:                        8.740   Durbin-Watson:                   0.956
Prob(Omnibus):                  0.013   Jarque-Bera (JB):               10.327
Skew:                           0.289   Prob(JB):                      0.00572
Kurtosis:                       3.733   Cond. No.                     8.53e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.53e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [21]:
# Problem 2.2 - Understanding the Model
# Compute the correlations between all the variables in the training set. 
# Question 1: Which of the following independent variables is N2O highly correlated with(absolute correlation greater than 0.7)?
# Options: MEI, CO2, CH4, CFC-11, CFC-12, Aerosols, TSI
# Question 2: Which of the following independent variables is CFC.11 highly correlated with? Select all that apply.
# Options: MEI, CO2, CH4, N2O, CFC-12, Aerosols, TSI

# correlation can be check by calling method corr on dataframe
train_data.corr()

,Year,Month,MEI,CO2,CH4,N2O,CFC-11,CFC-12,TSI,Aerosols,Temp
Year,1.000000,-0.027942,-0.036988,0.982749,0.915659,0.993845,0.569106,0.897012,0.170302,-0.345247,0.786797
Month,-0.027942,1.000000,0.000885,-0.106732,0.018569,0.013632,-0.013111,0.000675,-0.034606,0.014890,-0.099857
MEI,-0.036988,0.000885,1.000000,-0.041147,-0.033419,-0.050820,0.069000,0.008286,-0.154492,0.340238,0.172471
CO2,0.982749,-0.106732,-0.041147,1.000000,0.877280,0.976720,0.514060,0.852690,0.177429,-0.356155,0.788529
CH4,0.915659,0.018569,-0.033419,0.877280,1.000000,0.899839,0.779904,0.963616,0.245528,-0.267809,0.703255
N2O,0.993845,0.013632,-0.050820,0.976720,0.899839,1.000000,0.522477,0.867931,0.199757,-0.337055,0.778639
CFC-11,0.569106,-0.013111,0.069000,0.514060,0.779904,0.522477,1.000000,0.868985,0.272046,-0.043921,0.407710
CFC-12,0.897012,0.000675,0.008286,0.852690,0.963616,0.867931,0.868985,1.000000,0.255303,-0.225131,0.687558
TSI,0.170302,-0.034606,-0.154492,0.177429,0.245528,0.199757,0.272046,0.255303,1.000000,0.052117,0.243383
Aerosols,-0.345247,0.014890,0.340238,-0.356155,-0.267809,-0.337055,-0.043921,-0.225131,0.052117,1.000000,-0.384914
Temp,0.786797,-0.099857,0.172471,0.788529,0.703255,0.778639,0.407710,0.687558,0.243383,-0.384914,1.000000

In [24]:
# Problem 3 - Simplifying the Model
# Given that the correlations are so high, let us focus on the N2O variable and build a model with only MEI, TSI, Aerosols \
# and N2O as independent variables. 
X2 = sm.add_constant(train_data[["N2O", "MEI", "TSI","Aerosols"]])
regTemp2 = sm.OLS(train_data["Temp"], X2).fit()
regTemp2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   Temp   R-squared:                       0.726
Model:                            OLS   Adj. R-squared:                  0.722
Method:                 Least Squares   F-statistic:                     184.9
Date:                Fri, 02 Oct 2020   Prob (F-statistic):           3.52e-77
Time:                        06:46:08   Log-Likelihood:                 266.64
No. Observations:                 284   AIC:                            -523.3
Df Residuals:                     279   BIC:                            -505.0
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -116.2269     20.223     -5.747      0.000    -156.036     -76.418
N2O            0.0253      0.001     19.307      0.000       0.023       0.028
MEI            0.0642      0.007      9.649      0.000       0.051       0.077
TSI            0.0795      0.015      5.344      0.000       0.050       0.109
Aerosols      -1.7017      0.218     -7.806      0.000      -2.131      -1.273
==============================================================================
Omnibus:                       10.908   Durbin-Watson:                   0.842
Prob(Omnibus):                  0.004   Jarque-Bera (JB):               15.097
Skew:                           0.289   Prob(JB):                     0.000527
Kurtosis:                       3.971   Cond. No.                     5.00e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large,  5e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [26]:
regTemp.aic

-542.2023033074463

In [1]:
# Problem 4 - Automatically Building the Model
# using R step function, compare and find good model. Now python does not have R equivalent step function. So have skipped this 
# for time being. There are ways to achieve this in python.

In [ ]:
# Problem 5 - Testing on Unseen Data
# Using the model produced from the step function, calculate temperature predictions for the testing data set, using \ 
# the predict function.
# i have to skip this one as well since its dependent on problem 4.
sm.pr